#!/usr/bin/env python3
"""
Convert LinearFold C++ energy parameter headers into Rust static constants.
Only the -Dlv (Vienna integer) model is supported.
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
INCLUDE = ROOT / "include"
OUT = ROOT / "linearfold_rust" / "src" / "params.rs"


def strip_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    text = re.sub(r"//.*", "", text)
    return text


def extract_int_arrays(text: str, vie_inf: int):
    text = text.replace("VIE_INF", str(vie_inf))
    text = text.replace("NBPAIRS", "7")
    # Find each `int NAME[D1][D2]... = { ... };`
    decl_re = re.compile(r"int\s+(\w+)\s*((?:\[\s*[^\]]+?\s*\])+?)\s*=\s*\{", re.DOTALL)
    arrays = {}
    pos = 0
    for m in decl_re.finditer(text):
        name = m.group(1)
        dims_str = m.group(2)
        dims = []
        for expr in re.findall(r"\[\s*([^\]]+?)\s*\]", dims_str):
            expr = expr.strip()
            # Evaluate simple integer expressions like "7+1" or "5"
            dims.append(eval(expr, {"__builtins__": None}, {}))
        start = m.end() - 1  # position of '{'
        depth = 0
        i = start
        while i < len(text):
            if text[i] == "{":
                depth += 1
            elif text[i] == "}":
                depth -= 1
                if depth == 0:
                    break
            i += 1
        body = text[start + 1 : i]
        nums = [int(x) for x in re.findall(r"-?\d+", body)]
        expected = 1
        for d in dims:
            expected *= d
        if len(nums) != expected:
            raise ValueError(
                f"Array {name}{dims_str}: expected {expected} ints, got {len(nums)}"
            )
        arrays[name] = (dims, nums)
    return arrays


def extract_loops(text: str):
    loops = {}
    text = strip_comments(text)
    for name, kmer_len in [("Triloops", 5), ("Tetraloops", 6), ("Hexaloops", 8)]:
        # Match `char Triloops[...] =` followed by one or more string literals.
        decl_re = re.compile(rf'char\s+{name}\[\d+\]\s*=\s*("[^"]*"\s*)+;')
        m = decl_re.search(text)
        if not m:
            continue
        literals = re.findall(r'"([^"]*)"', m.group(0))
        raw = "".join(literals).replace(" ", "")
        seqs = [raw[i : i + kmer_len] for i in range(0, len(raw), kmer_len)]
        loops[name] = seqs
    return loops


def format_array(name: str, dims: list[int], nums: list[int]) -> str:
    assert dims
    ty = "i32"
    # Rust array type: [[i32; inner]; outer]
    rust_type = "i32"
    for d in reversed(dims):
        rust_type = f"[{rust_type}; {d}]"
    lines = []
    lines.append(f"pub static {name}: {rust_type} = ")

    def build(level: int, idx: int) -> tuple[str, int]:
        indent = "    " * (level + 1)
        if level == len(dims) - 1:
            vals = nums[idx : idx + dims[level]]
            line = indent + "[" + ", ".join(str(v) for v in vals) + "]"
            return line, idx + dims[level]
        parts = []
        next_idx = idx
        for _ in range(dims[level]):
            part, next_idx = build(level + 1, next_idx)
            parts.append(part)
        inner = ",\n".join(parts)
        return (
            indent + "[\n" + inner + "\n" + "    " * level + "]",
            next_idx,
        )

    body, final_idx = build(0, 0)
    assert final_idx == len(nums)
    lines.append(body + ";")
    return "\n".join(lines)


def format_loops(loops: dict) -> str:
    lines = []
    for name, seqs in loops.items():
        lines.append(f'pub static {name}: &[&str] = &[')
        for s in seqs:
            lines.append(f'    "{s}",')
        lines.append("];\n")
    return "\n".join(lines)


def main():
    out_lines = [
        "// AUTO-GENERATED by scripts/convert_params.py",
        "// Do not edit by hand.",
        "",
        "pub const VIE_INF: i32 = 10_000_000;",
        "pub const INTL_VIE_INF: i32 = 999_999_999;",
        "pub const NBPAIRS: usize = 7;",
        "pub const LXC37: f64 = 107.856;",
        "pub const ML_INTERN37: i32 = -90;",
        "pub const ML_CLOSING37: i32 = 930;",
        "pub const ML_BASE37: i32 = 0;",
        "pub const MAX_NINIO: i32 = 300;",
        "pub const NINIO37: i32 = 60;",
        "pub const TERMINAL_AU37: i32 = 50;",
        "",
    ]

    # energy_parameter.h
    ep_text = strip_comments((INCLUDE / "energy_parameter.h").read_text())
    ep_arrays = extract_int_arrays(ep_text, vie_inf=10_000_000)
    ep_loops = extract_loops(ep_text)
    for name, (dims, nums) in ep_arrays.items():
        out_lines.append(format_array(name, dims, nums))
        out_lines.append("")
    out_lines.append(format_loops(ep_loops))

    # intl*.h
    for header, vie_inf in [
        ("intl11.h", 999_999_999),
        ("intl21.h", 999_999_999),
        ("intl22.h", 999_999_999),
    ]:
        text = strip_comments((INCLUDE / header).read_text())
        arrays = extract_int_arrays(text, vie_inf)
        for name, (dims, nums) in arrays.items():
            out_lines.append(format_array(name, dims, nums))
            out_lines.append("")

    OUT.write_text("\n".join(out_lines))
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
